### ISSUE TITLE
undefined local variable or method `slider'

### ISSUE THREAD

**Issue by sfcgeorge** [spree-contrib/spree_slider#12]
With a relatively fresh Spree 3.0 and slider install I get this error on the homepage.

```
undefined local variable or method `slider'
```

It's coming from the [_slider partial](https://github.com/spree-contrib/spree_slider/blob/3-0-stable/app/views/spree/shared/_slider.html.erb#L1) because in the default [Deface override](https://github.com/spree-contrib/spree_slider/blob/3-0-stable/app/overrides/spree/home/index/add_slider.html.erb.deface#L3) the local variable `slider` isn't passed in as the Readme suggests.

Overriding the override fixed it, but it would be better if it works out of the box.

Either the partial should check for the `slider` variable, or the override should pass it in.

**Comment by jspizziri** [comment]
@sfcgeorge would you like to submit a PR for this?

If not I'll get to it as soon as I can.

**Comment by sfcgeorge** [comment]
Sure, I just wanted to make sure you didn't already have something in the works :) I've found a few more bugs I'm happy to PR, all in those 2 files so I can do them all as one PR if you're happy, with separate sub commits perhaps.

**Comment by jspizziri** [comment]
That would be awesome! one PR is fine.
