### ISSUE TITLE
solidus_slider error

### ISSUE THREAD

**Issue by krunalinnovify** [spree-contrib/spree_slider#19]
Hi, 

When i am using gem 'solidus_slider', github: 'spree-contrib/solidus_slider'  than perform bundle install.
i am getting error.

Git error: command `git clone 'git://github.com/spree-contrib/solidus_slider.git'

Thanks.

**Comment by damianlegawiec** [comment]
@krunalinnovify this gem is only for spree, not solidus, repo you're trying to fetch doesn't exist, use spree -> https://github.com/spree/spree if you want to use this gem
