### ISSUE TITLE
Remove support for options other than 'roll your own'?

### ISSUE THREAD

**Issue by joshuapaling** [spree-contrib/spree_slider#2]
This repo was moved to spree-contrib based on https://github.com/priviterag/spree_slider/issues/12

Early in that thread, @JDutil mentions he thinks this extension should only support rolling your own slider. I'd agree. There's potentially infinite ways to roll your own, and it's relatively easy. The integration of a means to add / edit slides with the Spree admin area is the harder / unique feature that this plugin offers.

If we're agreed it's a good approach to remove support for other sliders, I'm happy to do that and submit a PR. Thoughts?

**Comment by JDutil** [comment]
Now that Spree 3 rc is out this could be done.

**Comment by jspizziri** [comment]
@joshuapaling, Are you still interested in submitting a PR for this?

Now that the extension has been upgraded to 3.0 I think that it would be a very appropriate time.

**Comment by joshuapaling** [comment]
@jspizziri realistically I'm probably not going to find time to do this in the near future, sorry.

**Comment by jspizziri** [comment]
Fixed by #10
