### ISSUE TITLE
Installing spree_slider

### ISSUE THREAD

**Issue by lucasmazzetto** [spree-contrib/spree_slider#25]
Hello everyone, 
Well, when I try to run the bundle install appears some error messages about spree version:

"Could not find gem 'spree_backend (~> 3.2.0.alpha)' in any of the gem sources listed in your Gemfile or available on this machine."

Of course that i'm not using 3.2.0.alpha version (i'm using 3.1.0.rc3), but i want to run spree_slider with spree 3.1.0.rc3. How do i do that?

Regards

**Comment by damianlegawiec** [comment]
Hi @lucasmazzetto

please add this to your Gemfile:

```
gem 'spree_slider', github: 'spree-contrib/spree_slider', branch: '3-1-stable'
```

**Comment by lucasmazzetto** [comment]
Thanks @damianlegawiec!
