### ISSUE TITLE
Slider inserts at the wrong position

### ISSUE THREAD

**Issue by aravindratna93** [spree-contrib/spree_slider#8]
i've installed Spree_slider succesfully and everything works fine according to the functionality,
But the problem it is getting inserted between the header and navbar
but i want to insert it after the nav bar
Can you guys suggest me how to proceed
![image](https://cloud.githubusercontent.com/assets/8010770/7677949/f8030bc0-fd6d-11e4-9220-34b297d1eddc.png)
something like this

**Comment by jspizziri** [comment]
This has to do with where you're rendering the slider in your template.

**Comment by jspizziri** [comment]
@aravindratna93, did you solve you problem? If so I'm going to close this issue (I consider silence to be consent).

**Comment by webchi** [comment]
Issue like this. But slider generates it self in the   <%= yield %>, not only where I render it (top image).

![screenshot_20161214_190111](https://cloud.githubusercontent.com/assets/27108/21189464/e176e27c-c22f-11e6-9823-cf93f0af2940.png)
